name: "📖 User Story"
description: Issue for describing a user story.
title: "[US] "
labels:
  - story
type: "User Story"
projects: ["AVENIRS-Project/16", "AVENIRS-Project/3"]

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Cette User Story doit être prête (Definition of Ready) avant développement.

        ## Description de la User Story

  - type: textarea
    id: user_story
    attributes:
      label: "User Story"
      description: "Formalisme standard, description et critères d'acceptation"
      value: |
        **Formalisation: **
        En tant que ...
        Je souhaite ...
        Afin de ...

        **Description**
        Décrire précisément le comportement attendu


        **Critères d'acceptation**
        Given ...
        When ...
        Then ...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: ui_elements
    attributes:
      label: UI Elements
      placeholder: "[Lien Figma](URL_figma)"

  - type: textarea
    id: technical_notes
    attributes:
      label: "Notes techniques"
      description: "Contraintes ou indications pour l'équipe technique"
      placeholder: "Optionnel"
    validations:
      required: false


  - type: markdown
    attributes:
      value: |
        ### Référentiels projet

        - Definition of Ready (DoR) :
          https://avenirs-esr.github.io/dev-doc/quality/definition-of-ready-fr/

        - Definition of Done (DoD) :
          https://avenirs-esr.github.io/dev-doc/quality/definition-of-done-fr/
