name: "💳 Technical Debt"
description: Issue for identifying and addressing technical debt.
title: '[TECH-DEBT] '
labels:
  - tech-debt
type: "Enabler Story"
projects: ["AVENIRS-Project/16", "AVENIRS-Project/3"]

body:

  - type: dropdown
    id: debt_type
    attributes:
      label: "Type de dette"
      description: "Catégoriser la dette technique"
      options:
        - Code
        - Architecture
        - Tests
        - Documentation
        - DevOps
    validations:
      required: true

  - type: dropdown
    id: impact_level
    attributes:
      label: "Niveau d'impact technique"
      description: "Impact réel sur le système ou l'équipe"
      options:
        - 🔴 Bloquant
        - 🟠 Dégradant
        - 🟡 Gênant
        - 🟢 Mineur
    validations:
      required: true

  - type: textarea
    id: origine
    attributes:
      label: "Origine ou cause"
      description: "Pourquoi cette dette existe-t-elle ?"
      placeholder: "Dette historique, contrainte projet, dette intentionnelle..."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "Impact détaillé"
      description: "Impact sur code, performance, maintenabilité, DX..."
      placeholder: "Ex : complexité accrue, ralentissement, dette de test..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Propositions de refactoring ou amélioration"
      description: "Solutions envisagées"
      placeholder: "Refactoring module X, suppression dépendance Y..."
    validations:
      required: false

  - type: textarea
    id: risques
    attributes:
      label: "Risques ou dépendances"
      description: "Points de vigilance"
      placeholder: "Migration DB, dépendance externe..."
    validations:
      required: false

  - type: checkboxes
    id: done
    attributes:
      label: "Critères de complétion"
      options:
        - label: "Dettes identifiées traitées ou requalifiées"
        - label: "Tests ajustés ou ajoutés"
        - label: "Documentation mise à jour"

  - type: textarea
    id: ressources
    attributes:
      label: "Ressources associées"
      description: "Issues, PR, documentation..."
      placeholder: "#302, lien doc..."