name: "📋 Task"
description: Issue for tasks.
title: '[TASK] '
labels:
  - task
type: 'Task'
projects: ["AVENIRS-Project/16", "AVENIRS-Project/3"]

body:
  - type: markdown
    attributes:
      value: |
        ## Task:

        ⚠️ Attachez cette tâche comme sous-issue de la User Story (une fois créée, à droite dans l'issue, bouton "Relationships" puis "Add parent"), sinon elle ne sera jamais prise en compte par l'automatisation.
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: ui_elements
    attributes:
      label: Éléments UI de travail
      description: Ajouter lien Figma et/ou images
      placeholder: "[lien Figma](URL_figma)"
