name: "🧪 QUALIF Task"
description: Final task for MANUAL testing a User Story in dev environment before deployment in qualif.
title: "[QUALIF] Vérifier que l'US #<number> est complètement fonctionnelle sur dev"
labels:
  - Backend
  - Frontend
  - QUALIF
type: "Task"
projects: ["AVENIRS-Project/16"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🧪 QUALIF Task – Cofolio

        Validation MANUELLE finale d'une User Story en environnement de développement avant le déploiement en qualification.
        
        ⚠️ Attachez cette tâche comme sous-issue de la User Story (bouton "Add sub-issue" en bas à droite de l'issue), sinon elle ne sera jamais prise en compte par l'automatisation.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Énumérez les points de validation à vérifier dans l'environnement de développement.
      value: |
        Règles de gestion :
          - TODO: Répertorier toutes les RG de l'US

        Validation :
        Pour chaque RG, ajouter une preuve (capture d'écran, capture vidéo) de la bonne validation sur l'environnement dev
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Cette tâche validera la User Story dans l'environnement de développement avant le déploiement en qualification. Elle sera automatiquement ajoutée au projet « Cofolio ».
