name: "🧪 TEST Task"
description: Final task for E2E testing a User Story in dev environment before deployment in qualif.
title: "[TEST] Implémenter les tests E2E de l'US #<number>"
labels:
  - Backend
  - Frontend
  - TEST
type: "Task"
projects: ["AVENIRS-Project/16"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🧪 TEST Task – Cofolio

        Validation finale de bout en bout (E2E) d'une User Story dans l'environnement de développement avant le déploiement en qualification.

        ⚠️ Attachez cette tâche comme sous-issue de la User Story (une fois créée, à droite dans l'issue, bouton "Relationships" puis "Add parent"), sinon elle ne sera jamais prise en compte par l'automatisation.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: List the validation items to be checked in dev environment
      value: |
        - [ ] ⚠️ Implémenter les tests E2E (simples: affichage de la page et des éléments en lien avec le back)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Cette tâche validera la User Story dans l'environnement de développement avant le déploiement en qualification. Elle sera automatiquement ajoutée au projet « Cofolio ».

