name: "🐞 Bug Report"
description: Help us identify and fix bugs by filling out the details below.
title: "[Bug]: <short title>"
labels:
  - bug
  - needs-triage
type: "bug"
projects: ["AVENIRS-Project/16", "AVENIRS-Project/3"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report – Cofolio

        Please fill out the following fields as thoroughly as possible.
  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: Brief description of the problem.
      placeholder: "Cofolio does not save portfolios correctly..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the bug? List each step only (no screenshot here). 
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "The portfolio should be saved and visible in the dashboard."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens? Provide also screenshot
      placeholder: |
        Describe at least one of these items
        a description: The dashboard remains empty after saving.
        a screenshot: Paste de screenshot here
        a stacktrace: Paste the error/console stacktrace
    validations:
      required: true
  - type: input
    id: related_issue
    attributes:
      label: Related Issue
      description: If not createed from a US, reference the issue this BUG is related to
      value: "US #"
      placeholder: | 
        US : #issue_number
  - type: input
    id: env
    attributes:
      label: Environment
      description: Details on browser, version, OS, etc.
      placeholder: "Chrome 118, Windows 10"
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improving Cofolio! This issue will be automatically added to the 'Cofolio inter-sprint' project.
