name: "🐞 Bug Report"
description: Help us identify and fix bugs by filling out the details below.
title: "[Bug]: <short description>"
labels:
  - bug
  - needs-triage
type: "bug"
projects: ["AVENIRS-Project/16", "AVENIRS-Project/3"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report – Cofolio

        Please fill out the following fields as thoroughly as possible.
  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: Brief description of the problem.
      placeholder: "Cofolio does not save portfolios correctly..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the bug? List each step.
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "The portfolio should be saved and visible in the dashboard."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "The dashboard remains empty after saving."
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: Stacktrace
      description: If applicable, a stacktrace to help explain your problem.
  - type: input
    id: related_issue
    attributes:
      label: Related Epic
      description: Reference the epic number this story is related to
      value: "Epic : #"
      placeholder: | 
        Epic : #issue_number
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      description: Details on browser, version, OS, etc.
      placeholder: "Chrome 118, Windows 10"
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain the problem.
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improving Cofolio! This issue will be automatically added to the 'Cofolio inter-sprint' project.
