name: Epic
description: Issue for epics.
title: "[EPIC]: "
labels: 
  - Epic
projects: ["Cofolio", "MC2I - kaban"]
body:
  - type: textarea
    attributes:
      label: Description
      value: A concise description of the epic 
