name: Epic
about: Issue for epics.
title: '[EPIC]: '
labels: 
  - Epic
type: ''
projects: ["Cofolio", "MC2I - kaban"]
assignees: ''
body:
  - type: markdown
    attributes:
      value: "### Description"
