name: User Story
description: Issue for describing a user stories.
title: "[US]: "
labels: 
  - Story
type: "User Story"
projects: ["Cofolio", "MC2I - kaban"]
body:
  - type: input
    id: epic
    attributes:
      label: Epic
      description: point to the epic issue by #
      placeholder: "#"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Description de la User Story

  - type: textarea
    id: role
    attributes:
      label: **Description**
      description: Phrase d'introduction de la fonctionnalité
      value: |      
        **En tant que [role],**
        **Je veux [une action ou fonctionnalité],**
        **Afin de [plus-value/bénéfice ou résulat].**
      render: markdown

  - type: textarea
    id: criteria
    attributes:
      label: **Critères d'acceptance**
      description: Lister les critères d'acceptance
      value: |      
        - [ ] Critère 1: Describe the first acceptance criterion here.
        - [ ] Critère 2: Describe the second acceptance criterion here.
        - [ ] Critère 3: Describe additional criteria as needed.
      render: markdown
  - type: textarea
    id: dod
    attributes:
      label: **Definition du fini (DoD):**
      description: Definition of the Done
      value: |      
        - [ ] Criètes d'acceptance tous remplis.
        - [ ] Code revu et approuvé .
        - [ ] Tests automatisés necessaires écrit et passés avec couverture suffisante
        - [ ] Documentation mise à jour, si applicable.
        - [ ] Fonctionnalité déployée dans l'environnement de [environment name].

      render: markdown        
  - type: textarea
    id: infos
    attributes:
      label: Éléments UI de travail
      description: Placer ici une image
      value: |
        [Lien Figma](URL_figma)
      render: markdown

