name: "💳 Technical Debt"
description: Issue for identifying and addressing technical debt.
title: '[TECH-DEBT] '
labels:
  - tech-debt
type: "Enabler Story"
projects: ["AVENIRS-Project/16", "AVENIRS-Project/3"]

body:
  - type: markdown
    attributes:
      value: |
        ## Epic lié

        [🔗 AVENIRS-Project #302](https://github.com/orgs/avenirs-esr/projects/18/views/1?pane=issue&itemId=115434471&issue=avenirs-esr%7CAVENIRS-Project%7C302)
  - type: textarea
    id: origine
    attributes:
      label: "Origine ou cause"
      description: "Pourquoi cette dette existe-t-elle ?"
      placeholder: "Dette historique, contrainte projet, dette intentionnelle..."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "Impact"
      description: "Impact sur code, performance, maintenabilité, DX..."
      placeholder: "Ex : ralentissement build, complexité, bugs..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Propositions de refactoring ou amélioration"
      description: "Solutions envisagées"
      placeholder: "Refactoring module X, suppression dépendance Y..."
    validations:
      required: false

  - type: textarea
    id: risques
    attributes:
      label: "Risques ou dépendances"
      description: "Points de vigilance"
      placeholder: "Migration DB, dépendance externe..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |     

        ## Critères de complétion

        - [ ] Dettes identifiées traitées ou requalifiées
        - [ ] Tests ajustés ou ajoutés
        - [ ] Documentation mise à jour si nécessaire
  - type: textarea
    id: ressources
    attributes:
      label: "Ressources associées"
      description: "Issues, PR, documentation..."
      placeholder: "#302, lien doc..."
