name: "🧪 TEST Task"
description: Final task for testing a User Story in dev environment before deployment in qualif.
title: "[TEST] <short description>"
labels:
  - Backend
  - Frontend
  - TEST
type: "task"
projects: 
  - https://github.com/orgs/avenirs-esr/projects/16
body:
  - type: markdown
    attributes:
      value: |
        ## 🧪 TEST Task – Cofolio

        Final validation of a User Story in dev environment before deployment in qualification.
  - type: input
    id: story_number
    attributes:
      label: Story Number
      description: Reference the story this test is related to
      placeholder: "123"
    validations:
      required: true
  - type: textarea
    id: test_items
    attributes:
      label: Validation Items
      description: List the validation items to be checked in dev environment
      value: |
        - [ ] Item 1
        - [ ] Item 2
        - [ ] Item 3
        - [ ] Item 4
    validations:
      required: true
  - type: input
    id: parent_issue
    attributes:
      label: Parent Issue
      description: Reference the parent issue number
      placeholder: "123"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        This task will validate the User Story in dev environment before qualification deployment. It will be automatically added to the 'Cofolio' project.
name: "🧪 Test Task"
description: Create a test task to validate a story or feature.
title: "[TEST] <short description>"
labels:
  - Backend
  - Frontend
  - TEST
type: "task"
projects: 
  - https://github.com/orgs/avenirs-esr/projects/16
body:
  - type: markdown
    attributes:
      value: |
        ## 🧪 Test US - Cofolio

        Please fill out the following fields to create a test task.
  - type: input
    id: story_number
    attributes:
      label: Story Number
      description: Reference the story this test is related to
      placeholder: "123"
    validations:
      required: true
  - type: textarea
    id: test_items
    attributes:
      label: Test Items
      description: List the test items to be checked
      value: |
        - [ ] Item 1
        - [ ] Item 2
        - [ ] Item 3
        - [ ] Item 4
    validations:
      required: true
  - type: input
    id: parent_issue
    attributes:
      label: Parent Issue
      description: Reference the parent issue number
      placeholder: "123"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for helping us testing Cofolio! This issue will be automatically added to the 'Cofolio' project.
