name: "Check US completion"

on:
  issues:
    types: [closed]

permissions:
  contents: read
  issues: write
  repository-projects: write

jobs:
  call_remote:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/check-us-completion-workflow.yaml@main
    with:
      issue_node_id: ${{ github.event.issue.node_id }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_TOKEN: ${{ secrets.GH_APP_TOKEN }}
