name: "Reopen parent US when sub-issue is opened or reopened"

on:
  issues:
    types: [opened, reopened]

permissions:
  contents: read
  issues: write
  repository-projects: write

jobs:
  call_remote:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/reopen-us-workflow.yaml@main
    with:
      issue_node_id: ${{ github.event.issue.node_id }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_TOKEN: ${{ secrets.GH_APP_TOKEN }}

  check_issue_type:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/bug-task-creation-workflow.yaml@main
    with:
      issue_node_id: ${{ github.event.issue.node_id }}
    secrets:
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_TOKEN: ${{ secrets.GH_APP_TOKEN }}
      ROCKETCHAT_API_URL: ${{ secrets.ROCKETCHAT_API_URL }}
      ROCKETCHAT_TOKEN: ${{ secrets.ROCKETCHAT_TOKEN }}
      ROCKETCHAT_USER_ID: ${{ secrets.ROCKETCHAT_USER_ID }}