name: "Update US table in Wiki"

on:
  push:
    branches:
      - main

jobs:
  update:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/update-wiki-from-project-workflow.yaml@fix/wiki-automation
    with:
      org: avenirs-esr
      project_number: "3"
      wiki_page: "4-‐-2-‐-Spécifications-fonctionnelles-:-Apprenants.md"
      profile_label: "Profil : Apprenant"
      epic_label: "Epic"
    secrets: inherit
